### ISSUE TITLE
[UI Issue]: Graph disappears when resizing the window

### ISSUE THREAD

**Issue by mishaHype** [CrocSwap/ambient-ts-app#2572] opened 2023-06-28 20:32 UTC
### What happened?

When resizing the window the graph disappears (as intended) but when the window is resized back to its former size, the graph completly disappears.

### How?

Step 1: Open the Trade or pool tab while in a large window.
Step 2: Shrink the window untill it changes styles.
Step 3: Grow the window back to a large size.
Step 4: wonder where the graph went to (try switching tabs it will not re-appear)
Step 5: refresh and see graph again.

### What was Expected?

Expect the graph to return when the window is back to full size.

### What browser(s) are you seeing the problem on?

Chrome

### What wallet are you seeing the problem on?

MetaMask

**Comment by mishaHype** [comment] 2023-06-28 20:33
![Screenshot 2023-06-28 at 2 23 07 PM](https://github.com/CrocSwap/ambient-ts-app/assets/98827944/1daef6c0-99a4-4d44-9079-36d7e8e4b1c1)
![Screenshot 2023-06-28 at 2 22 56 PM](https://github.com/CrocSwap/ambient-ts-app/assets/98827944/11988107-3756-4e99-9fee-aac60146d359)
![Screenshot 2023-06-28 at 2 22 43 PM](https://github.com/CrocSwap/ambient-ts-app/assets/98827944/4736bfac-79b4-40d4-8b45-e4d053b9ddd0)

**Comment by enwong10** [comment] 2023-06-28 21:33
That's the view when the trade table is expanded, the chart can be found by clicking the minimize trade table button beside the "My Transactions" toggle... what I'm more curious about is why the header looks like its space between when it should left align 🤔

**Comment by mishaHype** [comment] 2023-06-29 14:07
Ah i see, is that more a UX issue then? as its very confusing on how to get the chart back since things are expected to go back to previous state when theres 0 interaction with the page to actively change the layout?

**Comment by mishaHype** [comment] 2023-06-29 14:12
![Screenshot 2023-06-29 at 10 11 38 AM](https://github.com/CrocSwap/ambient-ts-app/assets/98827944/139d2e13-2e53-465b-a21e-fa313d8d2820)
![Screenshot 2023-06-29 at 10 11 17 AM](https://github.com/CrocSwap/ambient-ts-app/assets/98827944/47c6468a-8d63-489f-9816-153ae179c927)

**Comment by mishaHype** [comment] 2023-06-29 14:12
I see also that the heart icon does not allign correctly when in expanded table view

**Comment by surudhb** [comment] 2023-07-05 18:40
duplicate of #2611

**Closed by surudhb** 2023-07-05 18:40 UTC
Labels: bug, low-prio
